# Generated by Django 3.2.7 on 2022-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20220228_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='url_images',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
